# fly.toml app configuration file generated for phonebook-app-fullstackopen-cortez on 2025-08-16T16:00:12-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-app-fullstackopen-cortez'
primary_region = 'iad'

[build]


[env]
PORT = "3001"


[http_service]
internal_port = 3001
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']
# health check at /api/health
# [[http_service.checks]]
# grace_period = "10s"
# interval = "1440m0s"
# method = "GET"
# path = "/health"
# timeout = "5s"

[[vm]]
size = 'shared-cpu-1x'
